# Site settings
title: Clayton Mottley
description: 'Virginia Tech - Mechanical Engineering'
url: 'http://joshgerdes.com/jekyll-uno'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Clayton Mottley'
  email: claymot@vt.edu
  github_username:  mottley

# defaults:
#   -
#     scope:
#       path: ''
#       type: 'posts'
#     values:
#         layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed
include: ['_pages']

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
